global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.2

update_frequency: 5.0
publish_frequency: 2.0 #vase local cost map in moheme ke beroz beshe --> hamin baes mishe hamra ba robot in window harkat kune - in to halat default 0 hast 

rolling_window: true
width: 5
height: 5

resolution: 0.05

origin_x: 0.0
origin_y: 0.0
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]


plugins:
  - {name: obstacle , type: costmap_2d::ObstacleLayer}
  - {name: inflation , type: costmap_2d::InflationLayer}

obstacle:
  observation_sources: scan
  scan: {topic: base_scan , sensor_frame: base_laser_link , data_type: LaserScan ,  clearing: true }


inflation:
  inflation_radius: 0.55
  cost_scaling_factor: 10
