plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: /map

inflation:
  inflation_radius: 0.4
  cost_scaling_factor: 2