global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.2

origin_x: 0.0
origin_y: 0.0

resolution: 0.05


static_map: true
rolling_window: false

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]

plugins:
  - {name: static , type: "costmap_2d::StaticLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}


static:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: "map"

inflation:
  inflation_radius: 0.55
  cost_scaling_factor: 10
